apiVersion: v1
kind: Service
metadata:
  name: monapp-service
spec:
  type: NodePort
  selector:
    app: monapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30522
      # NodePort automatique entre 30000-32767, ou tu peux fixer un port spécifique :
      # nodePort: 31000
